baseURL: https://yentingli.netlify.app
title: Yenting Li
paginate: 10
theme: PaperMod
hasCJKLanguage: true

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
      - HTML
      - RSS
      - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Yenting Li's blog
  description: "Yenting Li's blog"
  keywords: [Blog, Portfolio]
  author: Yenting Li
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  # ShowReadingTime: true
  # ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  ShowToc: true
  TocOpen: true
  # images: ["first_post.jpg"]
  homeInfoParams:
      Title: "Hi there \U0001F44B"
      Content: >
        Dad, husband, Soulslike games enjoyer.

  socialIcons:
      - name: github
        url: "https://github.com/yentingli?tab=repositories"
      - name: twitter
        url: "https://twitter.com/yentingli_"
      - name: Rss
        url: "index.xml"
  assets:
    disableHLJS: false # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "Home"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList:  false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  giscus:
    dataRepo: "yentingli/blog-hugo"
    dataRepoID: "R_kgDOH70gYQ"
    dataCategory: "Announcements"
    dataCategoryID: "DIC_kwDOH70gYc4CVeCM"
  cusdis:
    dataAppId: "d569735b-ab77-448c-ad1f-31439df844c7"


taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - identifier: search
      name: 🔍Search
      url: /search/
      weight: 1
    - identifier: Archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 25
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 30
    # - identifier: series
    #   name: Serires
    #   url: /series/
    #   weight: 40
    # - identifier: example
    #   name: Example.org
    #   url: https://example.org
    #   weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai